runtime: python39
service: default

instance_class: F1
entrypoint: gunicorn -b :$PORT -w 4 main:app

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

includes:
  - env_variables.yaml
